version: "3"
services:
  app-real:
    build: .
    ports:
      - "7007:7007"
    working_dir: /home
    volumes:
      - .:/home
      - D:\Prj\IGCM\Datasets2:/home/src/static
      # - cifs_mount_real:/home/src/static
  app-anime:
    build: .
    ports:
      - "7008:7007"
    working_dir: /home
    environment:
      - PUID=0
      - PGID=0
    user: root
    volumes:
      - .:/home
      - D:\Prj\IGCM\Datasets2A:/home/src/static
      # - cifs_mount_anime:/home/src/static
